---
title: "R Notebook"
output: html_notebook
---

```{r}
library(limma)
library(dplyr)
library(tidyr)
library(data.table)
library(broom)
library(broomExtra)
library(tibble)
library(sjstats)
library(car)
library(lme4)
library(lmerTest)
library(ggplot2)
library(tibble)
library(modelr)
library(tidyverse)
#library(miceadds)
library(ggforce)
require(openxlsx)
```

#### Read in Supplemental Table 1
```{r}
S1<-fread("/Users/shawjes/Dropbox/EspinosaGroup/ANALYSIS/MSD/Final/200512/Supplemental_Tables/MSD_082420_Supplemental_Table_1_v1.0_JRS.csv")
S1

#### Summarize the samples
S1 %>%
  select(RecordID, LabID, Karyotype) %>%
  unique() %>%
  group_by(Karyotype) %>%
  summarise(N=n())
```

#### Set theme for plots
```{r}
theme_set(theme_gray(base_size = 12, base_family = "Arial") +
            theme(panel.border = element_rect(colour="black", fill = "transparent"),
                  plot.title = element_text(face="bold", hjust = 0), # lineheight=.8, size=20,
                  axis.text = element_text(color="black", size = 10),
                  axis.text.x = element_text(angle = 0, hjust = 0.5),
                  panel.background = element_blank(),
                  panel.grid = element_blank(),
                  plot.background = element_blank()
            ) +
            theme(strip.background = element_rect(colour="black", fill = "light grey", size = 1)) # adjusts facet label borders
)
```

##### Produce Supplemental Figure 1B: Age distribution of individuals in the analysis dataset

##### Option 1: Histogram
```{r}
ageHist_byKaryotype<-S1 %>%
  filter(!is.na(Karyotype)) %>%
  ggplot( ) +
  geom_histogram(aes(x=Age_at_visit, color=Karyotype, fill=Karyotype ), alpha=0.4) +
  scale_fill_manual(values=c("grey", "#2b8cbe")) +
  scale_color_manual(values=c("grey", "#2b8cbe")) +
  theme(legend.position = "top",
        legend.title = element_blank(), legend.direction="horizontal") +
  xlab("Age at visit") +
  scale_x_continuous(breaks = seq(0, 60, 5)) +
  ggtitle("Age distribution of individuals in analysis dataset")

ageHist_byKaryotype

setwd("/Users/shawjes/Dropbox/EspinosaGroup/ANALYSIS/MSD/Final/200512/Supplemental_Figures")
ggsave(ageHist_byKaryotype, filename = paste("MSD_082420_S1B_AgeDistribution_Histogram_v1.0_JRS", ".png", sep=""),
       width = 6, height = 5, units = "in")
ggsave(ageHist_byKaryotype, filename = paste("MSD_082420_S1B_AgeDistribution_Histogram_v1.0_JRS", ".pdf", sep=""),
       device = cairo_pdf, width = 6, height = 5, units = "in")
```

##### Option 2: Scaled probability density plots
```{r}
ageDensity_byKaryotype<-S1 %>%
  filter(!is.na(Karyotype)) %>%
  ggplot( ) +
  geom_density(aes(x=Age_at_visit, y=..scaled.., color=Karyotype, fill=Karyotype ), alpha=0.4) +
  scale_fill_manual(values=c("grey", "#2b8cbe")) +
  scale_color_manual(values=c("grey", "#2b8cbe")) +
  theme(legend.position = "top",
        legend.title = element_blank(), legend.direction="horizontal") +
  xlab("Age at visit") +
  ylab("Scaled density") +
  scale_x_continuous(breaks = seq(0, 60, 5)) +
  ggtitle("Age distribution of individuals in analysis dataset")

ageDensity_byKaryotype

setwd("/Users/shawjes/Dropbox/EspinosaGroup/ANALYSIS/MSD/Final/200512/Supplemental_Figures")
ggsave(ageDensity_byKaryotype, filename = paste("MSD_082420_S1B_AgeDistribution_DensityPlot_v1.0_JRS", ".png", sep=""),
       width = 6, height = 5, units = "in")
ggsave(ageDensity_byKaryotype, filename = paste("MSD_082420_S1B_AgeDistribution_DensityPlot_v1.0_JRS", ".pdf", sep=""),
       device = cairo_pdf, width = 6, height = 5, units = "in")
```
