---
title: "R Notebook"
output: html_notebook
---

```{r}
#install.packages("renv")
```

```{r}
renv::init()
```

```{r}
renv::status()

#install.packages("yaml")
#renv::install("ade4")
# renv::install("dendextend")
# renv::install("emmeans")
# renv::install("factoextra")
# renv::install("glmnet")
# renv::install("mediation")
# renv::install("pathview")
# renv::install("UniprotR")
# renv::install("BiocInstaller") # Error: package 'BiocInstaller' is not available
# renv::install("broomExtra") # Error: package 'broomExtra' is not available
# renv::install("MXM") # Error: package 'MXM' is not available
```

```{r}
renv::snapshot()
```

```{r}
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
```

```{r}
# BiocManager::install("biomaRt",
#                      update = TRUE,
#                      ask = TRUE,
#                      force = TRUE) # a
# 
# BiocManager::valid("biomaRt")
```

```{r}
# BiocManager::install("clusterProfiler",
#                      update = TRUE,
#                      ask = TRUE,
#                      force = TRUE);
# 
# BiocManager::valid("clusterProfiler")
```

```{r}
# BiocManager::install("SomaScan.db",
#                      update = TRUE,
#                      ask = TRUE,
#                      force = TRUE)
```

```{r}
# BiocManager::install("AnnotationHub",
#                      update = TRUE,
#                      ask = TRUE,
#                      force = TRUE);
# 
# BiocManager::valid("AnnotationHub")
```

```{r}
# BiocManager::install("org.Hs.eg.db");
# 
# BiocManager::valid("org.Hs.eg.db")
```

```{r}
# BiocManager::install("ensembldb",
#                      update = TRUE,
#                      ask = TRUE,
#                      force = TRUE);
# 
# BiocManager::valid("ensembldb")
```


```{r}
#BiocManager::install("Bioconductor/BiocFileCache")
#install.packages("tidyverse")
# library(tidyverse)

# library(clusterProfiler)
# If you use clusterProfiler in published research, please cite:
# G Yu, LG Wang, Y Han, QY He. clusterProfiler: an R package for comparing biological themes among gene clusters. OMICS: A Journal of Integrative Biology 2012, 16(5):284-287. doi:[10.1089/omi.2011.0118](http://dx.doi.org/10.1089/omi.2011.0118)

# https://www.nature.com/articles/s41596-024-01020-z
# Xu et al., 2024: 'Using clusterProfiler to characterize multiomics data'

# BiocManager::install("pathview")
# BiocManager::install("GOSemSim")
# install.packages("reshape")

# https://rdrr.io/bioc/biomaRt/man/getGene.html
# BiocManager::install("biomaRt", dependencies = TRUE)

# https://help.synapse.org/docs/Installing-Synapse-API-Clients.1985249668.html

#pip install synapseclient

#synapse login "shawjr" "Bloombug2015!"
# Help documentation:
# synapse -h

#pip install synapseclient
```

```{r}
#install.packages("synapser", repos=c("http://ran.synapse.org", "https://cloud.r-project.org"))
#install.packages("synapser")

#library(synapser)
#synLogin("username", "password")
```

```{r}
#source("https://bioconductor.org/biocLite.R")
#source("https://bioconductor.org/biocLite.R")

#BiocInstaller::biocLite("clusterProfiler")
```

