---
title: "R Notebook"
output: html_notebook
---

#### Obtain P4C metadata from Donovan et al. 2024:
# https://www.nature.com/articles/s41467-024-49781-1#Sec40

#### Run startup function
```{r}
setwd("~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/macro")
source("ui_init.R")
```

#### Define paths to directories
```{r}
dir.donovan2024_source <- "~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/rawdata/Donovan2024_syn31481952.5"

dir.project <- "~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev"
dir.indata <- paste0(dir.project, "/indata")
dir.aidata <- paste0(dir.project, "/aidata")
dir.ardata <- paste0(dir.project, "/ardata")
dir.ddata <- paste0(dir.project, "/dddata")
```

#### Read aidata
```{r}
setwd(dir.aidata)
ai_p4c_meta <- fread("ai_p4c_meta.csv.gz")
ai_p4c_soma_anno <- fread("ai_p4c_soma_anno.csv.gz")
ai_p4c_soma <- fread("ai_p4c_soma.csv.gz")

setwd(dir.aidata)
ai_aptamer_chromosomes <- fread("ai_aptamer_chromosomes.csv.gz")

setwd(dir.aidata)
ai_proteomic_clock_proteins_clusters <- fread("ai_proteomic_clock_proteins_clusters.csv.gz") %>%
  dplyr::rename(Lehallier2019_clusterID = ClusterID,
         Lehallier_Variable = Variable) %>%
  mutate(aptamer_in_Lehallier2019 = 1)

ai_p4c_meta
ai_p4c_soma
ai_p4c_soma_anno
ai_proteomic_clock_proteins_clusters
```

#### ar_p4c_soma
```{r}
ar_p4c_soma <- ai_p4c_soma %>%
  mutate(aptamer_in_p4c_soma = 1) %>%
  left_join(ai_p4c_soma_anno, by = c("Aptamer", "UniProt", "GeneSymbol")) %>%
  left_join(ai_p4c_meta, by = "LabID") %>%
  full_join(ai_proteomic_clock_proteins_clusters, by = c("Aptamer")) %>%
  mutate(Cluster = paste0("Cluster ", Lehallier2019_clusterID),
         Cluster = factor(Cluster,
                          levels = c("Cluster 7",
                                     "Cluster 6", 
                                     "Cluster 3",
                                     "Cluster 4", 
                                     "Cluster 2", 
                                     "Cluster 1",
                                     "Cluster 5",
                                     "Cluster 8")),
         ggtitle = Cluster) %>%
  mutate(T21 = case_when(Karyotype == "T21" ~ 1,
                         Karyotype == "Control" ~ 0,
                         .default = NA),
         Female = case_when(Sex == "Female" ~ 1,
                            Sex == "Male" ~ 0,
                            .default = NA),
         Karyotype_Sex = paste(Karyotype, Sex, sep = " "),
         Karyotype_Sex = factor(Karyotype_Sex, levels = c("D21 Female", "D21 Male", "T21 Female", "T21 Male")),
         Karyotype_XY = gsub("Female", "XX", Karyotype_Sex),
         Karyotype_XY = gsub("Male", "XY", Karyotype_XY)) %>%
  mutate(Cluster = case_when(is.na(Cluster) ~ "Cluster Other", .default = Cluster)) %>%
  mutate(Aptamer_Chr_Cluster = paste0(Aptamer, " (Chr", chromosome, ", ", Cluster, ")"),
         UniProt_Aptamer_Chr_Cluster = paste0(UniProt, "|", Aptamer, " (Chr", chromosome, ", ", Cluster, ")")) %>%
  dplyr::select(UniProt_Aptamer_Chr_Cluster, Aptamer_Chr_Cluster, everything()) %>%
  dplyr::rename(Aptamer_in_p4c_soma = aptamer_in_p4c_soma,
         Aptamer_in_Lehallier2019 = aptamer_in_Lehallier2019) %>%
  mutate(# P01275|GCG.4891.50 (Chr2, Cluster 2)
          UniProt_Aptamer_Chr_Cluster = paste0(UniProt, "|", Aptamer, " (Chr", chromosome, ", ", Cluster, ")"),
         # GCG.4891.50 (Chr2, Cluster 2)
         Aptamer_Chr_Cluster = paste0(Aptamer, " (Chr", chromosome, ", ", Cluster, ")")) %>%
  dplyr::select(UniProt_Aptamer_Chr_Cluster, Aptamer_Chr_Cluster,
                Aptamer, chromosome, everything())

ar_p4c_soma

setwd(dir.ardata)
fwrite(ar_p4c_soma, "ar_p4c_soma.csv.gz")
```