---
title: "R Notebook"
output: html_notebook
---

#### Obtain P4C metadata from Donovan et al. 2024:
# https://www.nature.com/articles/s41467-024-49781-1#Sec40

#### Run startup function
```{r}
setwd("~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/macro")
source("ui_init.R")
```
#### Define paths to directories
```{r}
dir.donovan2024_source <- "~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/rawdata/Donovan2024_syn31481952.5"

dir.project <- "~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev"
dir.indata <- paste0(dir.project, "/indata")
dir.aidata <- paste0(dir.project, "/aidata")
dir.ardata <- paste0(dir.project, "/ardata")
dir.ddata <- paste0(dir.project, "/dddata")
```

#### Read P4C SomaLogic data downloaded from Synapse
```{r}
ar_p4c_soma <- fread("/Users/jessica/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/rawdata/HTP_SOMAscan_Proteomics_Synapse.txt",
                  sep = "\t")

ar_p4c_soma
```

#### ai_proteomic_clock_proteins_clusters
```{r}
# https://www.nature.com/articles/s41591-019-0673-2
# https://pmc.ncbi.nlm.nih.gov/articles/PMC7062043/#SD2
st7 <- openxlsx::read.xlsx("/Users/jessica/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/rawdata/NIHMS1541641-supplement-1541641_Sup_Tab1-17.xlsx",
                 sheet = 8, # "ST7 Plasma proteomic clock"
                 startRow = 2) %>% 
  `rownames<-`(NULL)

#install.packages("openxlsx")
#library(openxlsx)
st11_clusterIDs <- openxlsx::read.xlsx("/Users/jessica/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/rawdata/NIHMS1541641-supplement-1541641_Sup_Tab1-17.xlsx",
                 sheet = 12, # "ST7 Plasma proteomic clock"
                 startRow = 3) %>% 
  `rownames<-`(NULL)

proteomic_clock_proteins <- st7 %>% dplyr::select(Variable) %>% filter(Variable != "(Intercept)")

# st7
#st11_clusterIDs
#proteomic_clock_proteins

ai_proteomic_clock_proteins_clusters <- proteomic_clock_proteins %>%
  full_join(st11_clusterIDs, by = c("Variable" = "Protein")) %>%
  separate(Variable, into = paste0("v", seq(1:10)), remove = FALSE, extra = "merge") %>%
  gather(key = "key", value = "value", v1:v10) %>%
  mutate(value = case_when(is.na(value) ~ "", .default = value),
         key = gsub("v", "", key) %>% as.numeric()) %>%
  group_by(Variable, ClusterID) %>%
  arrange(Variable, key) %>%
  filter(value != "") %>%
  mutate(max_key = max(key)) %>%
  mutate(is_last_piece = case_when(key == max_key ~ 1, .default = 0)) %>%
  filter(is_last_piece == 0) %>%
  dplyr::select(-c(max_key, is_last_piece)) %>%
  mutate(key = paste0("v", key)) %>%
  summarise(Aptamer = paste(value, collapse = ".")) %>%
  ungroup() %>%
  dplyr::rename(Lehallier2019_ClusterID = ClusterID,
                Lehallier2019_Variable = Variable) %>%
  mutate(Aptamer_in_Lehallier2019 = 1);

rm(st11_clusterIDs, proteomic_clock_proteins); gc()

ai_proteomic_clock_proteins_clusters
```

```{r}
setwd(dir.aidata)
fwrite(ai_proteomic_clock_proteins_clusters, "ai_proteomic_clock_proteins_clusters.csv.gz")
```

