---
title: "R Notebook"
output: html_notebook
---

#### KEEP SCRIPT

#### Run startup function
```{r}
dir.project <- "~/Dropbox/ShawJR/2025/dev"

setwd(paste0(dir.project, "/macro"))
source("ui_init.R")

select <- dplyr::select;
filter <- dplyr::filter;
rename <- dplyr::rename;
```

#### Define paths to directories
```{r}
dir.project <- "~/Dropbox/ShawJR/2025/dev"
dir.donovan2024_source <- paste0(dir.project, "/rawdata/Donovan2024_syn31481952.5")
dir.indata <- paste0(dir.project, "/indata")
dir.aidata <- paste0(dir.project, "/aidata")
dir.ardata <- paste0(dir.project, "/ardata")
dir.ddata <- paste0(dir.project, "/ddata")
dir.docs <- paste0(dir.project, "/docs")
dir.output <- paste0(dir.project, "/output")
```

#### Read Analysis Tracker
```{r}
setwd(dir.docs)
analysis_tracker <- read.xlsx("AnalysisTracker.xlsx") %>%
  filter(run_model == 1)

analysis_tracker
```

#### ar_p4c_soma_sigt21byage_d21only_clustering_input
```{r}
#significance_threshold <- 0.10
significance_threshold <- 0.05

setwd(dir.ddata)
ar_p4c_soma_sigt21byage_d21only_clustering_input <- fread("t_p4c_soma_lm_singleaptamer_tidy.csv.gz") %>%
  filter(PadjBH<significance_threshold & term == "T21:Age") %>%
  left_join(fread(paste0(dir.ardata, "/ar_p4c_soma_d21only.csv.gz")),
            by = c("UniProt_Aptamer_Chr_Cluster", "UniProt", "Aptamer", "Cluster"))

setwd(dir.ardata)
fwrite(ar_p4c_soma_sigt21byage_d21only_clustering_input, "ar_p4c_soma_sigt21byage_d21only_clustering_input.csv.gz")
```

```{r}
#t_sigt21byage_aptamer_multiple_genesymbols <- 
  ar_p4c_soma_sigt21byage_d21only_clustering_input %>%
  dplyr::select(Aptamer, GeneSymbol) %>%
  unique() %>%
  arrange(GeneSymbol) %>%
  group_by(Aptamer) %>%
  separate(GeneSymbol,
           into = c(paste0("GeneSymbol", seq(1:4))),
           sep = " ", extra = "merge", remove = TRUE) %>%
  gather(key = "GeneSymbol_Index", value = "GeneSymbol", starts_with("GeneSymbol")) %>%
  ungroup() %>%
  filter(!is.na(GeneSymbol)) %>%
  group_by(Aptamer) %>%
  summarise(N_GeneSymbol_for_Aptamer = n()) %>%
  ungroup() %>%
  arrange(desc(N_GeneSymbol_for_Aptamer)) %>%
  filter(N_GeneSymbol_for_Aptamer > 1) %>%
  left_join( (ar_p4c_soma_sigt21byage_d21only_clustering_input %>%
                dplyr::select(Aptamer, GeneSymbol) %>%
                unique()),
             by = "Aptamer" )

# Note: For GSEA of proteins with more than one GeneSymbol per Aptamer, the first GeneSymbol listed will be used in the GSEA...
```

