---
title: "R Notebook"
output: html_notebook
---

#### Obtain P4C metadata from Donovan et al. 2024:
# https://www.nature.com/articles/s41467-024-49781-1#Sec40

#### Run startup function
```{r}
setwd("~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/macro")
source("ui_init.R")
```

#### Define paths to directories
```{r}
dir.donovan2024_source <- "~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev/rawdata/Donovan2024_syn31481952.5"

dir.project <- "~/Dropbox/EspinosaGroup/ANALYSIS/2025/dev"
dir.indata <- paste0(dir.project, "/indata")
dir.aidata <- paste0(dir.project, "/aidata")
dir.ardata <- paste0(dir.project, "/ardata")
dir.ddata <- paste0(dir.project, "/ddata")
dir.output <- paste0(dir.project, "/output")
```

#### Read ardata
```{r}
setwd(dir.ardata)
ar_p4c_soma_sumZcluster_t21only <- fread("ar_p4c_soma_sumZcluster_agepred_t21only.csv.gz") %>%
  dplyr::select(-c(sumZ_Cluster_Other))

ar_p4c_soma_sumZcluster_t21only
```

### Linear model for log(Age) vs. sumZ_Cluster_1 + ... + sumZ_Cluster8
```{r}
set.seed(1234)
fit.sumZcluster_agepred_t21only <- lm(log(Age) ~ sumZ_Cluster_1 +
                                        sumZ_Cluster_2 +
                                        sumZ_Cluster_3 +
                                        sumZ_Cluster_4 +
                                        sumZ_Cluster_5 +
                                        sumZ_Cluster_6 +
                                        sumZ_Cluster_7 +
                                        sumZ_Cluster_8 +
                                        #sumZ_Cluster_Other +
                                        Female,
                                data = ar_p4c_soma_sumZcluster_t21only);
```

```{r}
dd_augment_sumZcluster_agepred_t21only <- fit.sumZcluster_agepred_t21only %>%
  augment(newdata = ar_p4c_soma_sumZcluster_t21only) %>%
  mutate(model_formula = "log(Age) ~ sumZ_Cluster_1 +
                                        sumZ_Cluster_2 +
                                        sumZ_Cluster_3 +
                                        sumZ_Cluster_4 +
                                        sumZ_Cluster_5 +
                                        sumZ_Cluster_6 +
                                        sumZ_Cluster_7 +
                                        sumZ_Cluster_8 +
                                        Female") %>%
  dplyr::select(model_formula, everything());
dd_augment_sumZcluster_agepred_t21only

dd_glance_sumZcluster_agepred_t21only <- fit.sumZcluster_agepred_t21only %>% glance() %>%
  mutate(model_formula = "log(Age) ~ sumZ_Cluster_1 +
                                        sumZ_Cluster_2 +
                                        sumZ_Cluster_3 +
                                        sumZ_Cluster_4 +
                                        sumZ_Cluster_5 +
                                        sumZ_Cluster_6 +
                                        sumZ_Cluster_7 +
                                        sumZ_Cluster_8 +
                                        Female") %>%
  dplyr::select(model_formula, everything());
dd_glance_sumZcluster_agepred_t21only

dd_tidy_sumZcluster_agepred_t21only <- fit.sumZcluster_agepred_t21only %>%
  tidy(conf.int = TRUE) %>%
  filter(term!="(Intercept)") %>%
  dplyr::rename(log10FC = estimate,
         P = p.value) %>%
  #select(-c(std.error, statistic)) %>%
  arrange(P) %>%
  mutate(model_formula = "log(Age) ~ sumZ_Cluster_1 +
                                        sumZ_Cluster_2 +
                                        sumZ_Cluster_3 +
                                        sumZ_Cluster_4 +
                                        sumZ_Cluster_5 +
                                        sumZ_Cluster_6 +
                                        sumZ_Cluster_7 +
                                        sumZ_Cluster_8 +
                                        Female") %>%
  dplyr::select(model_formula, everything());

setwd(dir.ddata)
fwrite(dd_augment_sumZcluster_agepred_t21only, "dd_augment_sumZcluster_agepred_t21only.csv")
fwrite(dd_glance_sumZcluster_agepred_t21only, "dd_glance_sumZcluster_agepred_t21only.csv")
fwrite(dd_tidy_sumZcluster_agepred_t21only, "dd_tidy_sumZcluster_agepred_t21only.csv")

dd_augment_sumZcluster_agepred_t21only
dd_glance_sumZcluster_agepred_t21only
dd_tidy_sumZcluster_agepred_t21only
```
