---
title: "R Notebook"
output: html_notebook
---

# KEEP SCRIPT

#### Run startup function
```{r}
dir.project <- "~/Dropbox/ShawJR/2025/dev"

setwd(paste0(dir.project, "/macro"))
source("ui_init.R")

select <- dplyr::select;
filter <- dplyr::filter;
rename <- dplyr::rename;
```

#### Define paths to directories
```{r}
dir.project <- "~/Dropbox/ShawJR/2025/dev"
dir.donovan2024_source <- paste0(dir.project, "/rawdata/Donovan2024_syn31481952.5")
dir.indata <- paste0(dir.project, "/indata")
dir.aidata <- paste0(dir.project, "/aidata")
dir.ardata <- paste0(dir.project, "/ardata")
dir.ddata <- paste0(dir.project, "/ddata")
dir.docs <- paste0(dir.project, "/docs")
dir.output <- paste0(dir.project, "/output")
```

#### Read Analysis Tracker
```{r}
setwd(dir.docs)
analysis_tracker <- read.xlsx("AnalysisTracker.xlsx") %>%
  filter(run_model == 1)

analysis_tracker
```

#### ar_sigt21byage_d21clustered
```{r}
setwd(dir.ardata)
ar_sigt21byage_d21clustered <- fread("ar_sigt21byage_d21clustered_v2.0.csv.gz") # IMPORTANT - NOTE V2.0 IS ONLY CHANGE IN THIS SCRIPT

#ar_sigt21byage_d21clustered.split %>% head()
```

#### f_sigt21byage_d21clustered
```{r}
# head(ar_sigt21byage_d21clustered)

f_sigt21byage_d21clustered <- ar_sigt21byage_d21clustered %>%
  mutate(gg_title = paste0("T21-by-Age Cluster ", T21byAge_Cluster),
         gg_subtitle = paste0("(N=", N_Cluster_Aptamers, " Aptamers with FDR<0.05)"))

# f_sigt21byage_d21clustered
f_sigt21byage_d21clustered.split <- f_sigt21byage_d21clustered %>% split(., .$T21byAge_Cluster)

setwd(dir.ddata)
fwrite(f_sigt21byage_d21clustered, "f_sigt21byage_d21clustered_v2.0.csv.gz") # IMPORTANT NOTE THE CORRESPONDING V2.0 IN OUTPUT FILENAME
```


```{r}
gg_trajectory_bykt_sigt21byage_cluster <- list()
gg_trajectory_byktsex_sigt21byage_cluster <- list()
for ( i in 1:length(f_sigt21byage_d21clustered.split) ) {
  gg_trajectory_bykt_sigt21byage_cluster[[i]] <- f_sigt21byage_d21clustered.split[[i]] %>%
    ggplot(aes(x = Age, y = Zlog10_relative_abundance, color = Karyotype, fill = Karyotype)) +
    geom_smooth(method = "loess", linewidth = 0.75, se = TRUE) +
    scale_colour_manual(values = c(RedBlue)) +
    scale_fill_manual(values = c(RedBlue)) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    theme(aspect.ratio = 1.0,
        legend.position = "bottom") +
    ylab("Relative abundance (Zlog10)") +
    #facet_wrap(~T21byAge_Cluster, ncol=4) +
    #ggtitle(paste0("T21-by-Age Cluster ", names(f_sigt21byage_d21clustered.split)[[i]])) +
    theme(aspect.ratio = 1.0,
          legend.position = "bottom",
          legend.title = element_blank()) +
    labs(title = element_text(unique(f_sigt21byage_d21clustered.split[[i]]$gg_title)),
         subtitle = element_text(unique(f_sigt21byage_d21clustered.split[[i]]$gg_subtitle)));
  save_as <- paste0("f_trajectory_bykt_sigt21byage_cluster_",
                    names(f_sigt21byage_d21clustered.split)[[i]]);
  setwd(dir.output)
  ggsave(gg_trajectory_bykt_sigt21byage_cluster[[i]],
       filename = paste0(save_as, "_v2.0.png"), # IMPORTANT: "_v2.0.png"
       width = 5, height = 5, units = "in")

  gg_trajectory_byktsex_sigt21byage_cluster[[i]] <- f_sigt21byage_d21clustered.split[[i]] %>%
    ggplot(aes(x = Age, y = Zlog10_relative_abundance, color = Karyotype_Sex, fill = Karyotype_Sex)) +
    geom_smooth(method = "loess", linewidth = 0.75, se = TRUE) +
    scale_colour_manual(values = c("pink3",
                                 RedBlue[[1]],
                                 "navy",
                                 RedBlue[[2]])) +
    scale_fill_manual(values = c("pink3",
                                 RedBlue[[1]],
                                 "navy",
                                 RedBlue[[2]])) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    theme(aspect.ratio = 1.0,
        legend.position = "bottom") +
    ylab("Relative abundance (Zlog10)") +
    #facet_wrap(~T21byAge_Cluster, ncol=4) +
    #ggtitle(paste0("T21-by-Age Cluster ", names(f_sigt21byage_d21clustered.split)[[i]])) +
    theme(aspect.ratio = 1.0,
          legend.position = "bottom",
          legend.title = element_blank()) +
    labs(title = element_text(unique(f_sigt21byage_d21clustered.split[[i]]$gg_title)),
         subtitle = element_text(unique(f_sigt21byage_d21clustered.split[[i]]$gg_subtitle)));
  save_as <- paste0("f_trajectory_byktsex_sigt21byage_cluster_",
                    names(f_sigt21byage_d21clustered.split)[[i]]);
  setwd(dir.output)
  ggsave(gg_trajectory_byktsex_sigt21byage_cluster[[i]],
       filename = paste0(save_as, "_v2.0.png"),
       width = 5, height = 5, units = "in")
}
```


```{r}
# n_aptamers <- "_n_"
gg_trajectory_byktsex_sigt21byage_cluster_facet <- ar_sigt21byage_d21clustered %>%
  mutate(Karyotype = factor(Karyotype, levels = c("D21", "T21")),
         `T21-by-Age Cluster` = paste0("T21-by-Age Cluster ", T21byAge_Cluster, "\n(N=", N_Cluster_Aptamers, " Aptamers with FDR<0.05)"),
         Karyotype_Sex = factor(Karyotype_Sex, c("D21 XX", "D21 XY", "T21 XX", "T21 XY"))) %>%
  arrange(Karyotype) %>%
  ggplot(aes(x = Age, y = Zlog10_relative_abundance, color = Karyotype_Sex, fill = Karyotype_Sex)) +
  geom_smooth(method = "loess", linewidth = 0.75, se = TRUE) +
  scale_colour_manual(values = c("pink3",
                                 RedBlue[[1]],
                                 "navy",
                                 RedBlue[[2]])) +
  scale_fill_manual(values = c("pink3",
                                 RedBlue[[1]],
                                 "navy",
                                 RedBlue[[2]])) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme(aspect.ratio = 1.0,
        legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(size = 12),
        plot.subtitle = element_text(size = 12)) +
  ylab("Relative abundance (Zlog10)") +
  facet_wrap(~`T21-by-Age Cluster`, ncol = 3);

save_as <- "f_trajectory_byktsex_sigt21byage_cluster_facet";
setwd(dir.output)
ggsave(gg_trajectory_byktsex_sigt21byage_cluster_facet,
       filename = paste0(save_as, "_v2.0.png"),
       width = 13, height = 13, units = "in")

gg_trajectory_byktsex_sigt21byage_cluster_facet_freescale <- ar_sigt21byage_d21clustered %>%
  mutate(Karyotype = factor(Karyotype, levels = c("D21", "T21")),
         `T21-by-Age Cluster` = paste0("T21-by-Age Cluster ", T21byAge_Cluster, "\n(N=", N_Cluster_Aptamers, " Aptamers with FDR<0.05)"),
         Karyotype_Sex = factor(Karyotype_Sex, c("D21 XX", "D21 XY", "T21 XX", "T21 XY"))) %>%
  arrange(Karyotype) %>%
  ggplot(aes(x = Age, y = Zlog10_relative_abundance, color = Karyotype_Sex, fill = Karyotype_Sex)) +
  geom_smooth(method = "loess", linewidth = 0.75, se = TRUE) +
  scale_colour_manual(values = c("pink3",
                                 RedBlue[[1]],
                                 "navy",
                                 RedBlue[[2]])) +
  scale_fill_manual(values = c("pink3",
                                 RedBlue[[1]],
                                 "navy",
                                 RedBlue[[2]])) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme(aspect.ratio = 1.0,
        legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(size = 12),
        plot.subtitle = element_text(size = 10.5)) +
  ylab("Relative abundance (Zlog10)") +
  facet_wrap(~`T21-by-Age Cluster`, ncol = 3, scales = "free");

save_as <- "f_trajectory_byktsex_sigt21byage_cluster_facet_freescale";
setwd(dir.output)
ggsave(gg_trajectory_byktsex_sigt21byage_cluster_facet_freescale,
       filename = paste0(save_as, "_v2.0.png"),
       width = 14, height = 14, units = "in")
```




