---
title: "R Notebook"
output: html_notebook
---
#### Run startup function
```{r}
dir.project <- "~/Dropbox/ShawJR/2025/dev"

setwd(paste0(dir.project, "/macro"))
source("ui_init.R")
```

#### Define paths to directories
```{r}
dir.project <- "~/Dropbox/ShawJR/2025/dev"
dir.donovan2024_source <- paste0(dir.project, "/rawdata/Donovan2024_syn31481952.5")
dir.indata <- paste0(dir.project, "/indata")
dir.aidata <- paste0(dir.project, "/aidata")
dir.ardata <- paste0(dir.project, "/ardata")
dir.ddata <- paste0(dir.project, "/ddata")
dir.docs <- paste0(dir.project, "/docs")
dir.output <- paste0(dir.project, "/output")
```

#### Read Analysis Tracker
```{r}
# setwd(dir.docs)
# analysis_tracker <- read.xlsx("AnalysisTracker.xlsx") %>%
#   filter(run_model == 1)
# 
# analysis_tracker
```



```{r}
setwd(dir.ddata)
f_p4c_soma_d21_clock_clusters_extended <- fread("f_p4c_soma_d21_clock_clusters_extended.csv.gz") %>%
  full_join(gg_cat, by = "UniProt_Aptamer_Chr_Cluster") %>%
  mutate(Clock_Cluster = factor(Clock_Cluster, levels = c(paste0("Clock Cluster ", seq(1:16)))),
         UniProt_Aptamer_Chr_Cluster = factor(UniProt_Aptamer_Chr_Cluster)) %>%
  #group_by(LabID) %>%
  #slice_sample(prop = 0.10) %>%
  #slice_sample(n = 10) %>%
  arrange(Clock_Cluster, UniProt_Aptamer_Chr_Cluster) %>%
  ungroup() %>%
  # Note: Object 'P4C_extended_cluster_colors' is loaded by ui_init.R
  mutate(gg_color = case_when(Clock_Cluster == "Clock Cluster 1" ~ P4C_extended_cluster_colors[[1]],
                              Clock_Cluster == "Clock Cluster 2" ~ P4C_extended_cluster_colors[[2]],
                              Clock_Cluster == "Clock Cluster 3" ~ P4C_extended_cluster_colors[[3]],
                              Clock_Cluster == "Clock Cluster 4" ~ P4C_extended_cluster_colors[[4]],
                              Clock_Cluster == "Clock Cluster 5" ~ P4C_extended_cluster_colors[[5]],
                              Clock_Cluster == "Clock Cluster 6" ~ P4C_extended_cluster_colors[[6]],
                              Clock_Cluster == "Clock Cluster 7" ~ P4C_extended_cluster_colors[[7]],
                              Clock_Cluster == "Clock Cluster 8" ~ P4C_extended_cluster_colors[[8]],
                              
                              Clock_Cluster == "Clock Cluster 9" ~ P4C_extended_cluster_colors[[9]],
                              Clock_Cluster == "Clock Cluster 10" ~ P4C_extended_cluster_colors[[10]],
                              Clock_Cluster == "Clock Cluster 11" ~ P4C_extended_cluster_colors[[11]],
                              Clock_Cluster == "Clock Cluster 12" ~ P4C_extended_cluster_colors[[12]],
                              Clock_Cluster == "Clock Cluster 13" ~ P4C_extended_cluster_colors[[13]],
                              Clock_Cluster == "Clock Cluster 14" ~ P4C_extended_cluster_colors[[14]],
                              Clock_Cluster == "Clock Cluster 15" ~ P4C_extended_cluster_colors[[15]],
                              Clock_Cluster == "Clock Cluster 16" ~ P4C_extended_cluster_colors[[16]],
                              .default = NA)) %>%
  arrange(Clock_Cluster, UniProt_Aptamer_Chr_Cluster) %>%
  ungroup();

f_p4c_soma_d21_clock_clusters_extended %>%
  arrange(Clock_Cluster, UniProt_Aptamer_Chr_Cluster) %>%
  dplyr::select(Clock_Cluster, UniProt_Aptamer_Chr_Cluster, gg_color) %>%
  unique() %>%
  split(., .$Clock_Cluster)

colors.now <- (f_p4c_soma_d21_clock_clusters_extended %>%
  arrange(Clock_Cluster, UniProt_Aptamer_Chr_Cluster) %>%
  dplyr::select(Clock_Cluster, UniProt_Aptamer_Chr_Cluster, gg_color) %>%
  arrange(Clock_Cluster, UniProt_Aptamer_Chr_Cluster) %>%
  unique())$gg_color
```

