---
title: "R Notebook"
output: html_notebook
---

#### Run startup function
```{r}
dir.project <- "~/Dropbox/ShawJR/2025/dev"

setwd(paste0(dir.project, "/macro"))
source("ui_init.R")
```

#### Define paths to directories
```{r}
dir.project <- "~/Dropbox/ShawJR/2025/dev"
dir.donovan2024_source <- paste0(dir.project, "/rawdata/Donovan2024_syn31481952.5")
dir.indata <- paste0(dir.project, "/indata")
dir.aidata <- paste0(dir.project, "/aidata")
dir.ardata <- paste0(dir.project, "/ardata")
dir.ddata <- paste0(dir.project, "/ddata")
dir.docs <- paste0(dir.project, "/docs")
```

#### Read Analysis Tracker
```{r}
setwd(dir.docs)
analysis_tracker <- read.xlsx("AnalysisTracker.xlsx") %>%
  filter(ddata_name == gsub(".Rmd", "", basename(rstudioapi::getSourceEditorContext()$path)) &
           run_model == 1) 

analysis_tracker
```

#### Read ardata
```{r}
setwd(dir.ardata)
ardata <- fread(paste0(unique(analysis_tracker$ardata_name), ".csv.gz"))
# Note these two lines should be the only revision to ardata before modeling.

ardata %>% dplyr::select(T21, Karyotype) %>% unique()
ardata
```
#### Vectorize model formulas to be fit
```{r}
tmp <- analysis_tracker %>%
  dplyr::select(model_formula) %>%
  unique() %>%
  #mutate(model_name = paste0("model", row_number())) %>%
  `rownames<-`(NULL);
model_formula <- tmp$model_formula;
names(model_formula) <- tmp$model_name;

model_formula
```

```{r}
lm_vif <- car::vif(lm(as.formula(model_formula), data = ardata)) %>%
  as.data.frame() %>%
  `colnames<-`("VIF") %>%
  rownames_to_column("term") %>%
  arrange(desc(VIF))%>%
  mutate(model_formula = model_formula,
         cohort = "T21 only") %>%
  dplyr::select(cohort, model_formula, everything());

lm_tidy <- tidy(lm(as.formula(model_formula), data = ardata)) %>%
  mutate(model_formula = model_formula,
         cohort = "T21 only") %>%
  dplyr::select(cohort, model_formula, everything()) %>%
  filter(term!="(Intercept)") %>%
  group_by(term) %>% # IMPORTANT: MUST GROUP BY BOTH TERM AND APTAMER.
  mutate(PadjBH = p.adjust(p.value, method = "BH")) %>%
  ungroup() %>%
  dplyr::rename(Zlog10FC = estimate, P = p.value) %>%
  dplyr::select(term, Zlog10FC, P, PadjBH, everything());

lm_glance <- glance(lm(as.formula(model_formula), data = ardata)) %>%
    mutate(model_formula = model_formula,
           cohort = "T21 only") %>%
    dplyr::select(cohort, model_formula, everything());

lm_augment <- augment(lm(as.formula(model_formula), data = ardata)) %>%
    mutate(model_formula = model_formula,
           cohort = "T21 only") %>%
    dplyr::select(cohort, model_formula, everything());

lm_vif
lm_tidy
lm_glance
lm_augment
```

```{r}
setwd(dir.ddata)
fwrite(lm_vif, "t_p4f_soma_lm_singlecluster_t21only_vif.csv.gz")
fwrite(lm_tidy, "t_p4f_soma_lm_singlecluster_t21only_tidy.csv.gz")
fwrite(lm_augment, "t_p4f_soma_lm_singlecluster_t21only_augment.csv.gz")
fwrite(lm_glance, "t_p4f_soma_lm_singlecluster_t21only_glance.csv.gz")
```