---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("renv")
```

```{r}
install.packages("yaml")
```

```{r}
renv::init()
```
```{r}
renv::status()
```

```{r}
renv::snapshot()
```


```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
```

```{r}
install.packages("BiocManager")
```

```{r}
BiocManager::install("biomaRt",
                     update = TRUE,
                     ask = TRUE,
                     force = TRUE) # a

BiocManager::valid("biomaRt")
```

```{r}
BiocManager::install("clusterProfiler",
                     update = TRUE,
                     ask = TRUE,
                     force = TRUE);

BiocManager::valid("clusterProfiler")
```

```{r}
BiocManager::install("AnnotationHub",
                     update = TRUE,
                     ask = TRUE,
                     force = TRUE);

BiocManager::valid("AnnotationHub")
```

```{r}
BiocManager::install("org.Hs.eg.db");

BiocManager::valid("org.Hs.eg.db")
```

```{r}
BiocManager::install("ensembldb",
                     update = TRUE,
                     ask = TRUE,
                     force = TRUE);

BiocManager::valid("ensembldb")
```




```{r}
#BiocManager::install("Bioconductor/BiocFileCache")
```

```{r}
#install.packages("tidyverse")
library(tidyverse)
```

```{r}
library(clusterProfiler)
# If you use clusterProfiler in published research, please cite:
# G Yu, LG Wang, Y Han, QY He. clusterProfiler: an R package for comparing biological themes among gene clusters. OMICS: A Journal of Integrative Biology 2012, 16(5):284-287. doi:[10.1089/omi.2011.0118](http://dx.doi.org/10.1089/omi.2011.0118)

# https://www.nature.com/articles/s41596-024-01020-z
# Xu et al., 2024: 'Using clusterProfiler to characterize multiomics data'
```

```{r}
BiocManager::install("pathview")
```

```{r}
BiocManager::install("GOSemSim")
```

```{r}
install.packages("reshape")
```

```{r}
# https://rdrr.io/bioc/biomaRt/man/getGene.html

# BiocManager::install("biomaRt", dependencies = TRUE)
```

```{bash}
# https://help.synapse.org/docs/Installing-Synapse-API-Clients.1985249668.html

pip install synapseclient

synapse login "shawjr" "Bloombug2015!"
# Help documentation:
# synapse -h

pip install synapseclient
```

```{r}
#install.packages("synapser", repos=c("http://ran.synapse.org", "https://cloud.r-project.org"))
#install.packages("synapser")

#library(synapser)
#synLogin("username", "password")
```

```{r}
source("https://bioconductor.org/biocLite.R")
source("https://bioconductor.org/biocLite.R")

BiocInstaller::biocLite("clusterProfiler")
```

